### ISSUE TITLE
Prepare for initial publication on Zenodo Sandbox

### ISSUE THREAD

**Issue by sdruskat** [sdruskat/cw23-hermes-demo#1]
Prepare the repository for the initial publication from the command line.

To do this, create a `hermes.toml` file in the repository root, and configure it for publication to Zenodo Sandbox.

```toml
[deposit]
mapping = "invenio"
target = "invenio"

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
api_paths = { depositions = "api/deposit/depositions", licenses = "api/licenses" }
schema_paths = { record = "api/schemas/records/record-v1.0.0.json" }
```

You also need to have a personal access token from Zenodo Sandbox.
