### ISSUE TITLE
Use GitHub Actions to automatically publish new versions on tags

### ISSUE THREAD

**Issue by sdruskat** [sdruskat/cw23-hermes-demo#3]
To automatically publish new versions to Zenodo Sandbox whenever a new tag is pushed, you can configure your repository to use GitHub Actions, and add a respective workflow configuration in `.github/workflows/hermes-zenodo-sandbox.yml` (see below).

You also have to add a Zenodo Sandbox personal token to the GitHub repository as a secret.

⚠️ **Note:** The shown configuration does not stop for curation before depositing. In real-life workflows, it would.

```yml
# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR), Helmholtz-Zentrum Drseden-Rossendorf, Forschungszentrum Jülich
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-FileContributor: Stephan Druskat

name: Software publication on Zenodo Sandbox

on:
  push:
    tags:
      - "*"

jobs:
  hermes:
    name: HERMES
    runs-on: ubuntu-latest
    permissions:
      contents: read # We will only read content from the repo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Install HERMES from GitHub
      - run: pip install git+https://github.com/hermes-hmc/workflow.git
      # Archive everything in the git repository into a zip file
      - run: git archive --format zip HEAD . > hermes.zip
      - run: hermes harvest
      - run: hermes process
      - run: hermes curate
      - run: hermes deposit --auth-token ${{ secrets.ZENODO_SANDBOX }} --file hermes.zip --file README.md
```
